### ISSUE TITLE
Ms Pacman implementation

### ISSUE THREAD

**Issue by Maathuis** [Maluuba/hra#3]
Hi, 

I would like to reproduce the results from the Ms Pacman environment.  Could you please upload the code to train/test your HRA method on this environment? If possible it would be nice to obtain the weights for the system (random and fixed start, without the use of the simplified version of executive memory). My goal is to use the trajectories for Inverse Reinforcement Learning purposes. It would greatly benefit my research if I am allowed to sample from this policy. 

Thank you for your consideration, 

Kind regards,
Henry

**Comment by fatemi** [comment]
Thank you for your interest. I fully understand the requests from the community for reproducing the results. The HRA codebase for Ms. Pacman requires considerable effort to become publishable, which is unfortunately not possible at this stage. However, the core is very similar to the one published here. You can also find all the weights we used in the supplementary materials of [the paper](https://arxiv.org/pdf/1706.04208.pdf) (page 13, section A.2).
